### ISSUE TITLE
Build broken - centres-cdk not in maven repo?

### ISSUE THREAD

**Issue by tdudgeon** [cdk/depict#6]
The build seems broken at the moment (both on master and the 0.3 tag).
It's failing because if can't find com.simolecule:centres-cdk:jar in the maven repo, and indeed that artifact does not seem to be in the OSSRH or Maven Central repos. 

[ERROR] Failed to execute goal on project cdkdepict: Could not resolve dependencies for project org.openscience.cdk:cdkdepict:war:0.3: Could not find artifact com.simolecule:centres-cdk:jar:0.1-SNAPSHOT in OSSRH (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by johnmay** [comment]
For now you need to install centres separately. 

```
git clone https://github.com/SiMolecule/centres && cd centres && mvn install -DskipTests
```

**Comment by johnmay** [comment]
I'll try and find time to put it on OSSRH this week though.

**Comment by johnmay** [comment]
Done, also pushed to docker hub

```docker run -p 8081:8080 simolecule/cdkdepict```

**Comment by tdudgeon** [comment]
Not sure this is sorted yet. The depict app is looking for is com.simolecule:centres-cdk:jar:0.1-SNAPSHOT but it looks like the artifacts can be found under:

https://oss.sonatype.org/content/repositories/snapshots/com/simolecule/centres/centres-cdk/0.1-SNAPSHOT/

(note the extra centres in the path). 

For me I still get this error when trying to do a `mvn assemble` on master or 0.3 tag:

[ERROR] Failed to execute goal on project cdkdepict: Could not resolve dependencies for project org.openscience.cdk:cdkdepict:war:0.3: Could not find artifact com.simolecule:centres-cdk:jar:0.1-SNAPSHOT in OSSRH (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

**Comment by johnmay** [comment]
Sorry yes, that is the correct fix. I had to change the group id for deploying to maven central and forgot to update it here.

**Comment by tdudgeon** [comment]
Thanks for the fix John. Works OK for me now.
